### ISSUE TITLE
NameError: name 'pooler_scale' is not defined

### ISSUE THREAD

**Issue by xinsuinizhuan** [hiennguyen9874/yolov7-mask#1]
python export.py --weights weights/yolov7-mask.pt --img-size 640 640 --batch-size 1 --grid --end2end --max-wh 640 --simplify --mask --cleanup --topk-all 100 --iou-thres 0.65 --conf-thres 0.35
 error:
C:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Model Summary: 399 layers, 45413366 parameters, 0 gradients, 176.4 GFLOPS

Starting ONNX export with onnx 1.11.0...
onnxruntime
xxx\yolov7-mask-mask\models\yolo.py:432: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.grid[i].shape[2:4] != x[0][i].shape[2:4]:
Traceback (most recent call last):
  File "xxx\yolov7-mask-mask\export.py", line 261, in <module>
    torch.onnx.export(
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\onnx\__init__.py", line 305, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\onnx\utils.py", line 118, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\onnx\utils.py", line 719, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\onnx\utils.py", line 499, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\onnx\utils.py", line 440, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\onnx\utils.py", line 391, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\jit\_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\jit\_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\jit\_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1098, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "E:\Item\Item_done\yolo\yolo5\yolov7\yolov7-mask\yolov7-mask-mask\models\experimental.py", line 835, in forward
    x = self.end2end(x)
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1098, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "xxx\yolov7-mask-mask\models\experimental.py", line 393, in forward
    pooler_scale,
NameError: name 'pooler_scale' is not defined

**Comment by hiennguyen9874** [comment]
Sorry, I fixed it.
